language: ruby
rvm: 2.1
android:
  components:
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - gem install fastlane
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
  - echo "run './flutter/bin/flutter test' command for test"
  - echo "run './flutter/bin/flutter build apk --release' command for build adroid apk app"
  - echo "run './flutter/bin/flutter build ios --release --no-codesign' command for build ios app"
cache:
  packages: true
  directories:
    - $HOME/.pub-cache
